### ISSUE TITLE
nginx报错如下，请问是什么问题呢

### ISSUE THREAD

**Issue by chenpe32cp** [vesoft-inc/nebula-graph-studio#204]
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf

10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf

/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh

/docker-entrypoint.sh: Configuration complete; ready for start up

2021/02/20 15:06:28 [crit] 1#1: pread() "/etc/nginx/conf.d/nebula.conf" failed (21: Is a directory)

nginx: [crit] pread() "/etc/nginx/conf.d/nebula.conf" failed (21: Is a directory)

10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled

2021/02/20 15:17:06 [crit] 1#1: pread() "/etc/nginx/conf.d/nebula.conf" failed (21: Is a directory)

2021/02/20 15:24:41 [crit] 1#1: pread() "/etc/nginx/conf.d/nebula.conf" failed (21: Is a directory)

**Comment by nianiaJR** [comment]
你看下是否能进入到这个 nginx容器，手动检查下 "/etc/nginx/conf.d/nebula.conf" 是否存在，正常情况下这个地方应该是空的，将会使用外面的 nginx 配置文件（https://github.com/vesoft-inc/nebula-web-docker/blob/master/nginx/nginx.conf）映射进去
