### ISSUE TITLE
v2.2.0浏览器支持问题

### ISSUE THREAD

**Issue by Godlikemandyy** [vesoft-inc/nebula-graph-studio#239]
我发现更新了v2.2.0后用搜狗浏览器打开出现以下情况：
![image](https://user-images.githubusercontent.com/36065226/115979536-0f59ac80-a5b9-11eb-8816-db8dc55450f7.png)
用谷歌没啥问题

**Comment by hetao92** [comment]
谢谢反馈，应该是浏览器对一些语法兼容性问题，我们会在后续修复

**Comment by hetao92** [comment]
你好，该问题已在 v2.2.1 中修复。烦请更新使用
