### ISSUE TITLE
控制台执行命令的输入框能否优化下

### ISSUE THREAD

**Issue by xiaoronghuang** [vesoft-inc/nebula-graph-studio#241]
输入框调大点改成可上下调整大小，现在太小了，查询语句长一点就不能看到整条语句了

**Comment by nianiaJR** [comment]
@hetao92 顺带改一下吧

**Comment by hetao92** [comment]
您好，该问题已在 v2.2.1 版本中修复，烦请更新后继续使用

**Comment by xiaoronghuang** [comment]
输入框现在可以调整大小了，但是重新编辑输入框内的内容，输入框就马上变回原来的大小 @nianiaJR @hetao92
