### ISSUE TITLE
通过studio 执行 show job “id” 无法显示结果

### ISSUE THREAD

**Issue by Eric2Vesoft** [vesoft-inc/nebula-graph-studio#245]
![截屏2021-05-12 下午2 38 58](https://user-images.githubusercontent.com/84064872/117930893-20344d00-b331-11eb-9dbf-f6c4d00adfef.png)
![截屏2021-05-12 下午2 39 35](https://user-images.githubusercontent.com/84064872/117930917-24606a80-b331-11eb-9c6e-f0d726d57d20.png)
![截屏2021-05-12 下午2 39 50](https://user-images.githubusercontent.com/84064872/117930926-288c8800-b331-11eb-8cd5-2923958fa4b6.png)

**Comment by Eric2Vesoft** [comment]
版本号：v2.1.9

**Comment by wey-gu** [comment]
Dear @Eric2Vesoft,
Thanks for reporting this.
Apart from your studio version `v2.1.9`, would you mind provide version information of the nebula-graph cluster?

Thanks!

**Comment by Eric2Vesoft** [comment]
Nebula Graph 2.0.1-ga

**Comment by Eric2Vesoft** [comment]
> Dear @Eric2Vesoft,
> Thanks for reporting this.
> Apart from your studio version `v2.1.9`, would you mind provide version information of the nebula-graph cluster?
> 
> Thanks!

nebula-graph-2.0.1.el7.x86_64.rpm

**Comment by wey-gu** [comment]
@nianiaJR :-)

**Comment by nianiaJR** [comment]
![image](https://user-images.githubusercontent.com/8124783/118481253-d939c380-b745-11eb-918b-cd494569a98f.png)
可以更新下最新安装包试试？我这里显示的是好的

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
