### ISSUE TITLE
Nebula Studio 无需正确用户名和密码就能登陆

### ISSUE THREAD

**Issue by Eric2Vesoft** [vesoft-inc/nebula-graph-studio#246]
![截屏2021-05-12 下午3 55 25](https://user-images.githubusercontent.com/84064872/117939345-870a3400-b33a-11eb-8056-120525399f73.png)
![截屏2021-05-12 下午4 01 25](https://user-images.githubusercontent.com/84064872/117940172-62628c00-b33b-11eb-96ae-4670eef988ae.png)

问题描述：只要Hosts填写正确，那么无论用户名和密码是否正确都可以登陆到操作界面，可以进行正常操作
版本：v2.1.9
部署方式：单机本地部署

**Comment by nianiaJR** [comment]
是不是没开启认证，默认nebula的认证是关闭的：https://docs.nebula-graph.com.cn/manual-CN/3.build-develop-and-administration/3.configurations/4.graph-config/#authorization
