### ISSUE TITLE
nebula Studio 连接数据库404 not found

### ISSUE THREAD

**Issue by snrui** [vesoft-inc/nebula-graph-studio#251]
登录Studio浏览器报错
![image](https://user-images.githubusercontent.com/72593964/118808175-c527ca80-b8db-11eb-86eb-21e6412fb3c2.png)
使用主机名:9669连接报错
![image](https://user-images.githubusercontent.com/72593964/118808666-5434e280-b8dc-11eb-8216-ef9fd88fe538.png)
后台服务状态正常
![image](https://user-images.githubusercontent.com/72593964/118808799-73337480-b8dc-11eb-982b-09a48a77da1b.png)
浏览器所在机器可以ping通Studio所在机器
telnet 主机名 9669可以连接
graphd日志报错invalid channel
![image](https://user-images.githubusercontent.com/72593964/118808940-99591480-b8dc-11eb-9847-9249640b43cf.png)
不知道这个报错是什么导致的，以及是不是这个报错导致配置失败

**Comment by nianiaJR** [comment]
用console连接正常么？

**Comment by snrui** [comment]
> 用console连接正常么？
console连接正常

**Comment by nianiaJR** [comment]
> > 用console连接正常么？
> > console连接正常

你的连接地址是什么样的？使用的啥版本？用什么方式启动的？有问题的话，到论坛来提吧：https://discuss.nebula-graph.com.cn/ 近期这个repo会关闭，日常答疑维护都在论坛🤝

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
