### ISSUE TITLE
控制台输入框依然有问题

### ISSUE THREAD

**Issue by vector233** [vesoft-inc/nebula-graph-studio#252]
#241 输入框现在可以调整大小了，但是重新编辑输入框内的内容，输入框就马上变回原来的大小 @nianiaJR @hetao92
issue被关闭@就没有提醒了吗，我有在原来的issue下回复，但是没有后续

**Comment by nianiaJR** [comment]
嗯，关闭了好像没有通知，我们看一下，有问题可以到论坛反馈，近期这个repo会下掉了

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
