### ISSUE TITLE
请求错误: 502 Bad Gateway

### ISSUE THREAD

**Issue by HeChuanXUPT** [vesoft-inc/nebula-graph-studio#254]
现象:
尝试执行某个查询请求之后, 就报错502, 再也无法选择space了

报错提示为: 请求错误: 502 Bad Gateway

F12网络里面显示:
Request URL: http://127.0.0.1:7001/api-nebula/db/exec
Request Method: POST
Status Code: 502 Bad Gateway
Payload: {"gql":"show spaces;"}

再点击页面都无法恢复
重启nebula-web-docker/v2服务可以恢复
```
docker-compose ps
状态都是UP
docker-compose down
docker-compose up -d
docker-compose ps
状态都是UP
```

**Comment by nianiaJR** [comment]
看起来nebula-http-gateway服务挂了，关掉服务重新部署一遍还不行么？

另外，目前这个仓库正在打算下掉，反馈问题的话，欢迎提到论坛：https://discuss.nebula-graph.com.cn/ 🤝

**Comment by HeChuanXUPT** [comment]
重新部署服务后是OK的, 但是一旦执行那条错误的查询语句就100%死掉, 我换到论坛重新提问下
thx
