### ISSUE TITLE
studio的源码在哪里？

### ISSUE THREAD

**Issue by wyw64962771** [vesoft-inc/nebula-graph-studio#257]
![image](https://user-images.githubusercontent.com/17894513/124467219-2511fc00-ddca-11eb-94da-fa27396d2fa9.png)
想对上面的资源进行一次转发，但是找到源码，只有docker-compose。

**Comment by nianiaJR** [comment]
the source code is not open now

**Comment by nianiaJR** [comment]
if you want to get the static source proxy， you can use the rpm setup mode to get the build dist

**Comment by wyw64962771** [comment]
那能用于商业化吗？
